/**
 * Workshop DIY — Anti-Drone System v1.2
 */
const $=id=>document.getElementById(id);const LIGHT_THEMES=['riad','medina'];
let soundEnabled=false;const AudioCtx=window.AudioContext||window.webkitAudioContext;let audioCtx;
function playSound(type){if(!soundEnabled)return;if(!audioCtx)audioCtx=new AudioCtx();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.connect(gain);gain.connect(audioCtx.destination);gain.gain.value=0.08;const t=audioCtx.currentTime;if(type==='click'){osc.frequency.value=800;osc.type='sine';gain.gain.exponentialRampToValueAtTime(0.001,t+0.08);osc.start(t);osc.stop(t+0.08);}else if(type==='success'){osc.frequency.value=523;osc.type='sine';gain.gain.exponentialRampToValueAtTime(0.001,t+0.3);osc.start(t);osc.stop(t+0.3);}else if(type==='error'){osc.frequency.value=200;osc.type='square';gain.gain.exponentialRampToValueAtTime(0.001,t+0.25);osc.start(t);osc.stop(t+0.25);}}
const LANG={
  en:{title:'Anti-Drone System',subtitle:'Anti-Drone System',disconnected:'Idle',connected:'Active',mainSection:'Anti-Drone RF System',mainDesc:'Detect, track, and neutralize drones via RF jamming',sectionA:'Drone Tracks',sectionB:'C-UAS Technology',activityLog:'Activity Log',eventsMsg:'Events',clear:'Clear',copy:'Copy',theme:'Theme',settings:'Settings',language:'Language',help:'Help',faq:'FAQ',howto:'How-To',wiki:'Wiki',faq_q1:'What is this app?',faq_a1:'A counter-drone RF system simulator for educational studies.',faq_q2:'How does C-UAS work?',faq_a2:'Detecting drone RF links and jamming control/video/GPS signals.',faq_q3:'Is this real?',faq_a3:'No. Visual simulation only.',faq_q4:'Data private?',faq_a4:'Yes. Everything runs locally.',howto_1:'Set radar range and sensitivity.',howto_2:'Start detection to find drones.',howto_3:'Select jamming band and power.',howto_4:'Engage jammer to neutralize.',working:'Working...',ready:'Anti-Drone System ready!',logCleared:'Log cleared',copied:'Copied!',copyFail:'Copy failed',export:'Export',filterAll:'All',soundEffects:'Sound effects',splashHint:'tap to skip',langChanged:'Language: English',themeChanged:'Theme:',startDetect:'Start Detection',stopDetect:'Stop Detection',engageJam:'Engage Jammer',disengageJam:'Disengage',resetSim:'Reset',detParams:'Detection',jamParams:'Jamming',radarRange:'Radar Range (km):',sensitivity:'Sensitivity:',jamPower:'Jam Power (W):',jamBand:'Jam Band:',sysStatus:'System Status',droneHint:'Tracked drone contacts and threat levels.'},
  fr:{title:'Systeme Anti-Drone',subtitle:'Systeme Anti-Drone',disconnected:'Inactif',connected:'Actif',mainSection:'Systeme RF Anti-Drone',mainDesc:'Detecter, suivre et neutraliser les drones',sectionA:'Pistes Drones',sectionB:'Technologie C-UAS',activityLog:'Journal',eventsMsg:'Evenements',clear:'Effacer',copy:'Copier',theme:'Theme',settings:'Parametres',language:'Langue',help:'Aide',faq:'FAQ',howto:'Guide',wiki:'Wiki',working:'En cours...',ready:'Systeme pret!',logCleared:'Journal efface',copied:'Copie!',copyFail:'Echec',export:'Exporter',filterAll:'Tout',soundEffects:'Effets sonores',splashHint:'appuyer pour passer',langChanged:'Langue: Francais',themeChanged:'Theme:',startDetect:'Demarrer Detection',stopDetect:'Arreter',engageJam:'Activer Brouilleur',disengageJam:'Desactiver',resetSim:'Reinitialiser'},
  ar:{title:'\u0646\u0638\u0627\u0645 \u0645\u0636\u0627\u062f \u0644\u0644\u0637\u0627\u0626\u0631\u0627\u062a',subtitle:'\u0646\u0638\u0627\u0645 \u0645\u0636\u0627\u062f \u0644\u0644\u0637\u0627\u0626\u0631\u0627\u062a',disconnected:'\u062e\u0627\u0645\u0644',connected:'\u0646\u0634\u0637',mainSection:'\u0646\u0638\u0627\u0645 RF \u0645\u0636\u0627\u062f \u0644\u0644\u0637\u0627\u0626\u0631\u0627\u062a',mainDesc:'\u0643\u0634\u0641 \u0648\u062a\u062a\u0628\u0639 \u0648\u062a\u062d\u064a\u064a\u062f \u0627\u0644\u0637\u0627\u0626\u0631\u0627\u062a \u0628\u062f\u0648\u0646 \u0637\u064a\u0627\u0631',sectionA:'\u0645\u0633\u0627\u0631\u0627\u062a \u0627\u0644\u0637\u0627\u0626\u0631\u0627\u062a',sectionB:'\u062a\u0643\u0646\u0648\u0644\u0648\u062c\u064a\u0627 C-UAS',activityLog:'\u0633\u062c\u0644',eventsMsg:'\u0623\u062d\u062f\u0627\u062b',clear:'\u0645\u0633\u062d',copy:'\u0646\u0633\u062e',theme:'\u0627\u0644\u0645\u0638\u0647\u0631',settings:'\u0625\u0639\u062f\u0627\u062f\u0627\u062a',language:'\u0627\u0644\u0644\u063a\u0629',help:'\u0645\u0633\u0627\u0639\u062f\u0629',faq:'\u0623\u0633\u0626\u0644\u0629',howto:'\u0643\u064a\u0641',wiki:'\u0648\u064a\u0643\u064a',working:'\u062c\u0627\u0631\u064d...',ready:'\u0627\u0644\u0646\u0638\u0627\u0645 \u062c\u0627\u0647\u0632!',logCleared:'\u062a\u0645 \u0627\u0644\u0645\u0633\u062d',copied:'\u062a\u0645!',copyFail:'\u0641\u0634\u0644',export:'\u062a\u0635\u062f\u064a\u0631',filterAll:'\u0627\u0644\u0643\u0644',soundEffects:'\u0645\u0624\u062b\u0631\u0627\u062a',splashHint:'\u0627\u0646\u0642\u0631',langChanged:'\u0627\u0644\u0644\u063a\u0629: \u0627\u0644\u0639\u0631\u0628\u064a\u0629',themeChanged:'\u0627\u0644\u0645\u0638\u0647\u0631:',startDetect:'\u0628\u062f\u0621 \u0627\u0644\u0643\u0634\u0641',stopDetect:'\u0625\u064a\u0642\u0627\u0641',engageJam:'\u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u0645\u0634\u0648\u0634',disengageJam:'\u0625\u064a\u0642\u0627\u0641',resetSim:'\u0625\u0639\u0627\u062f\u0629 \u062a\u0639\u064a\u064a\u0646'}
};
let currentLang='en';function setLanguage(lang){currentLang=lang;const s=LANG[lang];if(!s)return;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(s[k]!=null)el.textContent=s[k];});document.title=s.title+' — Workshop DIY';document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.lang=lang;const sel=$('langSelect');if(sel)sel.value=lang;try{localStorage.setItem('wdiy-lang',lang);}catch{}log(s.langChanged,'info');}
function setTheme(name){document.documentElement.dataset.theme=name;document.documentElement.classList.toggle('light-theme',LIGHT_THEMES.includes(name));const sel=$('themeSelect');if(sel)sel.value=name;try{localStorage.setItem('wdiy-theme',name);}catch{}log(LANG[currentLang].themeChanged+' '+name,'info');}
let logContainer;function log(msg,type='info'){if(!logContainer)logContainer=$('logContainer');if(!logContainer)return;const d=document.createElement('div');d.className='log-line '+type;d.textContent='['+new Date().toLocaleTimeString()+'] '+msg;logContainer.appendChild(d);logContainer.scrollTop=logContainer.scrollHeight;if(type==='success')playSound('success');else if(type==='error')playSound('error');applyLogFilter();}
function clearLog(){if(!logContainer)logContainer=$('logContainer');if(logContainer)logContainer.innerHTML='';log(LANG[currentLang].logCleared);}
async function copyLog(){if(!logContainer)logContainer=$('logContainer');if(!logContainer)return;try{await navigator.clipboard.writeText(Array.from(logContainer.children).map(d=>d.textContent).join('\n'));log(LANG[currentLang].copied,'success');}catch{log(LANG[currentLang].copyFail,'error');}}
function exportLog(){if(!logContainer)logContainer=$('logContainer');if(!logContainer)return;const blob=new Blob([Array.from(logContainer.children).map(d=>d.textContent).join('\n')],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cuas-log-'+new Date().toISOString().slice(0,10)+'.txt';a.click();}
let toastTimer=null;function showToast(msg,ms=0){const el=$('toastIndicator'),t=$('toastMessage');if(el&&t){t.textContent=msg||LANG[currentLang].working;el.style.display='block';}if(toastTimer)clearTimeout(toastTimer);if(ms>0)toastTimer=setTimeout(hideToast,ms);}function hideToast(){const el=$('toastIndicator');if(el)el.style.display='none';if(toastTimer){clearTimeout(toastTimer);toastTimer=null;}}
function setStatus(on){const pill=$('statusPill'),txt=$('statusText'),s=LANG[currentLang];if(txt)txt.textContent=on?s.connected:s.disconnected;if(pill)pill.classList.toggle('connected',on);}
let splashTimer;function dismissSplash(){const s=$('splash');if(!s)return;s.classList.add('hidden');if(splashTimer)clearTimeout(splashTimer);setTimeout(()=>s.remove(),600);playSound('click');}function initSplash(){const s=$('splash');if(!s)return;splashTimer=setTimeout(dismissSplash,2500);}
let activeLogFilter='all';function initLogFilters(){document.querySelectorAll('.log-filter').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.log-filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeLogFilter=btn.dataset.filter;applyLogFilter();playSound('click');});});}function applyLogFilter(){if(!logContainer)logContainer=$('logContainer');if(!logContainer)return;Array.from(logContainer.children).forEach(line=>{if(activeLogFilter==='all'){line.style.display='';return;}line.style.display=line.classList.contains(activeLogFilter)?'':'none';});}
function initPanels(){const hBtn=$('helpBtn'),hClose=$('helpCloseBtn'),hPanel=$('helpPanel'),hOver=$('helpOverlay');const sBtn=$('settingsBtn'),sClose=$('settingsCloseBtn'),sPanel=$('settingsPanel'),sOver=$('settingsOverlay');const lBtn=$('logBtn'),lClose=$('logCloseBtn'),lPanel=$('logPanel');if(hBtn)hBtn.onclick=()=>{hPanel.classList.toggle('open');hOver.classList.toggle('active');playSound('click');};if(hClose)hClose.onclick=()=>{hPanel.classList.remove('open');hOver.classList.remove('active');};if(hOver)hOver.onclick=()=>{hPanel.classList.remove('open');hOver.classList.remove('active');};if(sBtn)sBtn.onclick=()=>{sPanel.classList.toggle('open');sOver.classList.toggle('active');playSound('click');};if(sClose)sClose.onclick=()=>{sPanel.classList.remove('open');sOver.classList.remove('active');};if(sOver)sOver.onclick=()=>{sPanel.classList.remove('open');sOver.classList.remove('active');};if(lBtn)lBtn.onclick=()=>{lPanel.classList.toggle('open');playSound('click');};if(lClose)lClose.onclick=()=>lPanel.classList.remove('open');const langSel=$('langSelect'),themeSel=$('themeSelect'),sndTog=$('soundToggle');if(langSel)langSel.onchange=()=>setLanguage(langSel.value);if(themeSel)themeSel.onchange=()=>setTheme(themeSel.value);if(sndTog)sndTog.onchange=()=>{soundEnabled=sndTog.checked;};if($('clearLogBtn'))$('clearLogBtn').onclick=clearLog;if($('copyLogBtn'))$('copyLogBtn').onclick=copyLog;if($('exportLogBtn'))$('exportLogBtn').onclick=exportLog;document.querySelectorAll('.help-tab').forEach(tab=>{tab.addEventListener('click',()=>{document.querySelectorAll('.help-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');document.querySelectorAll('.help-content').forEach(c=>c.classList.remove('active'));const target=$('help'+tab.dataset.tab.charAt(0).toUpperCase()+tab.dataset.tab.slice(1));if(target)target.classList.add('active');playSound('click');});});}

let detecting=false,jamming=false,time=0;let drones=[];

function initDrones(){drones=[];const types=['Quadcopter','Hexacopter','Fixed-Wing','FPV Racer','Reconnaissance'];for(let i=0;i<6;i++){const angle=Math.random()*Math.PI*2;const dist=0.3+Math.random()*0.6;drones.push({id:'UAS-'+(i+1),type:types[Math.floor(Math.random()*types.length)],angle,dist,speed:0.002+Math.random()*0.005,alt:(50+Math.random()*400).toFixed(0),threat:['LOW','MED','HIGH'][Math.floor(Math.random()*3)],jammed:false,neutralized:false});}}

function drawRadar(){
  const c=$('radarCanvas');if(!c)return;const ctx=c.getContext('2d');const W=c.width,H=c.height;
  ctx.clearRect(0,0,W,H);ctx.fillStyle='#0a0a1a';ctx.fillRect(0,0,W,H);
  const cx=W/2,cy=H/2,R=Math.min(W,H)/2-30;
  // Rings
  for(let i=1;i<=4;i++){ctx.beginPath();ctx.arc(cx,cy,R*i/4,0,Math.PI*2);ctx.strokeStyle='rgba(0,255,136,0.12)';ctx.lineWidth=1;ctx.stroke();}
  ctx.beginPath();ctx.moveTo(cx-R,cy);ctx.lineTo(cx+R,cy);ctx.moveTo(cx,cy-R);ctx.lineTo(cx,cy+R);ctx.strokeStyle='rgba(0,255,136,0.08)';ctx.stroke();
  // Range labels
  const range=parseInt($('rangeInput')?.value||10);
  ctx.fillStyle='rgba(0,255,136,0.3)';ctx.font='8px Orbitron,monospace';ctx.textAlign='center';
  for(let i=1;i<=4;i++)ctx.fillText((range*i/4).toFixed(0)+'km',cx+R*i/4,cy+12);
  // Sweep
  if(detecting){const angle=time*1.5;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(angle)*R,cy+Math.sin(angle)*R);ctx.strokeStyle='rgba(0,255,136,0.5)';ctx.lineWidth=2;ctx.stroke();const grad=ctx.createRadialGradient(cx,cy,0,cx,cy,R);grad.addColorStop(0,'rgba(0,255,136,0.12)');grad.addColorStop(1,'rgba(0,255,136,0)');ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,R,angle-0.4,angle);ctx.closePath();ctx.fillStyle=grad;ctx.fill();}
  // Drones
  drones.forEach(d=>{
    d.angle+=d.speed;if(d.angle>Math.PI*2)d.angle-=Math.PI*2;
    if(d.neutralized){d.dist+=0.001;if(d.dist>1)d.dist=1;}
    const dx=cx+Math.cos(d.angle)*d.dist*R;const dy=cy+Math.sin(d.angle)*d.dist*R;
    if(!detecting&&!d.neutralized)return;
    const color=d.neutralized?'rgba(100,100,100,0.5)':d.jammed?'rgba(255,200,0,0.9)':d.threat==='HIGH'?'rgba(255,50,50,0.9)':d.threat==='MED'?'rgba(255,200,0,0.8)':'rgba(0,200,255,0.7)';
    ctx.beginPath();ctx.arc(dx,dy,6,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();
    if(d.threat==='HIGH'&&!d.neutralized&&detecting){ctx.beginPath();ctx.arc(dx,dy,12+Math.sin(time*5)*3,0,Math.PI*2);ctx.strokeStyle='rgba(255,50,50,0.5)';ctx.lineWidth=2;ctx.stroke();}
    if(d.jammed&&!d.neutralized){for(let j=0;j<3;j++){ctx.beginPath();ctx.arc(dx,dy,8+j*6+Math.sin(time*4)*2,0,Math.PI*2);ctx.strokeStyle='rgba(255,100,0,'+(0.3-j*0.08)+')';ctx.lineWidth=1;ctx.stroke();}}
    ctx.fillStyle=d.neutralized?'#666':d.jammed?'#ffcc00':'#66ccff';ctx.font='8px Orbitron,monospace';ctx.textAlign='center';ctx.fillText(d.id,dx,dy-10);
  });
  // Center
  ctx.beginPath();ctx.arc(cx,cy,8,0,Math.PI*2);ctx.fillStyle='rgba(0,255,136,0.8)';ctx.fill();ctx.fillStyle='rgba(0,255,136,0.6)';ctx.font='12px Orbitron,monospace';ctx.textAlign='left';ctx.fillText('C-UAS RADAR',10,18);
  if(jamming){ctx.fillStyle='rgba(255,100,0,0.8)';ctx.fillText('JAMMING ACTIVE',10,34);}
}

function drawRF(){
  const c=$('rfCanvas');if(!c)return;const ctx=c.getContext('2d');const W=c.width,H=c.height;
  ctx.clearRect(0,0,W,H);ctx.fillStyle='#0a0a1a';ctx.fillRect(0,0,W,H);
  // Show drone RF signatures
  ctx.beginPath();for(let x=0;x<W;x++){let y=H*0.7+Math.random()*6;if(detecting){const f=x/W*6;drones.forEach(d=>{if(d.neutralized)return;const dFreq=d.type==='FPV Racer'?5.8:2.4;if(Math.abs(f-dFreq)<0.3)y-=20+Math.random()*15;});}if(jamming){const band=$('jamBandSelect')?.value||'2.4ghz';const jf=band==='2.4ghz'?2.4:band==='5.8ghz'?5.8:band==='gps'?1.575:3;if(Math.abs(x/W*6-jf)<0.5)y-=30+Math.random()*20;}if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}
  ctx.strokeStyle='rgba(0,200,255,0.6)';ctx.lineWidth=1;ctx.stroke();
  ctx.fillStyle='rgba(0,255,136,0.5)';ctx.font='10px Orbitron,monospace';ctx.textAlign='left';ctx.fillText('RF SPECTRUM (0-6 GHz)',5,14);
}

function animate(){
  time+=0.016;
  if(jamming){drones.forEach(d=>{d.jammed=true;if(Math.random()>0.995&&!d.neutralized){d.neutralized=true;log('UAS '+d.id+' NEUTRALIZED','success');}});}
  drawRadar();drawRF();updateStats();requestAnimationFrame(animate);
}
function updateStats(){const stats=$('sysStats');if(!stats)return;const tracked=drones.filter(d=>detecting&&!d.neutralized).length;const neutralized=drones.filter(d=>d.neutralized).length;stats.innerHTML='<b>Tracked:</b> '+tracked+'<br><b>Neutralized:</b> '+neutralized+'<br><b>Jammer:</b> '+(jamming?'<span style="color:#ff8800">ENGAGED</span>':'OFF')+'<br><b>Status:</b> '+(detecting?'<span style="color:#00ff88">ACTIVE</span>':'<span style="color:#888">STANDBY</span>');}
function updateDroneList(){const lib=$('droneList');if(!lib)return;lib.innerHTML='';drones.forEach(d=>{const row=document.createElement('div');row.style.cssText='display:flex;justify-content:space-between;padding:3px 6px;border-radius:4px;font-size:.78rem;background:'+(d.neutralized?'rgba(100,100,100,0.1)':d.threat==='HIGH'?'rgba(255,50,50,0.1)':'rgba(0,200,255,0.05)');row.innerHTML='<span style="color:'+(d.neutralized?'#666':d.threat==='HIGH'?'#ff6666':'#66ccff')+'">'+d.id+'</span><span>'+d.type+'</span><span>'+d.alt+'m</span><span style="color:'+(d.threat==='HIGH'?'#ff4444':d.threat==='MED'?'#ffcc00':'#00cc88')+'">'+d.threat+'</span><span style="color:'+(d.neutralized?'#666':d.jammed?'#ff8800':'#00cc88')+'">'+(d.neutralized?'DOWN':d.jammed?'JAMMED':'TRACK')+'</span>';lib.appendChild(row);});}
function initTechDatabase(){const db=$('techDatabase');if(!db)return;db.innerHTML=['<b>RF Detection:</b> Identifying drone control and video link frequencies.','<b>2.4/5.8 GHz Jamming:</b> Disrupting WiFi and FPV control links.','<b>GPS Denial:</b> Blocking GPS to force drone return-to-home or land.','<b>Protocol Analysis:</b> Identifying drone make and model from RF signature.','<b>Directional Jamming:</b> Focused beam to minimize collateral disruption.','<b>Layered Defense:</b> Combining detection, tracking, and multiple countermeasures.'].join('<br><br>');}

function initControls(){
  $('rangeInput').oninput=()=>{$('rangeLabel').textContent=$('rangeInput').value+' km';};
  $('sensInput').oninput=()=>{$('sensLabel').textContent=$('sensInput').value+'%';};
  $('jamPowerInput').oninput=()=>{$('jamPowerLabel').textContent=$('jamPowerInput').value+' W';};
  $('detectBtn').onclick=()=>{detecting=!detecting;setStatus(detecting);$('detectBtn').querySelector('[data-i18n]').textContent=detecting?LANG[currentLang].stopDetect:LANG[currentLang].startDetect;log(detecting?'Detection STARTED — scanning for UAS':'Detection STOPPED',detecting?'rx':'info');if(detecting)showToast('Scanning...',2000);};
  $('jamBtn').onclick=()=>{jamming=!jamming;$('jamBtn').querySelector('[data-i18n]').textContent=jamming?LANG[currentLang].disengageJam:LANG[currentLang].engageJam;log(jamming?'JAMMER ENGAGED — '+$('jamBandSelect').value:'Jammer disengaged',jamming?'error':'info');if(jamming)showToast('Jamming...',2000);};
  $('resetBtn').onclick=()=>{detecting=false;jamming=false;setStatus(false);initDrones();$('detectBtn').querySelector('[data-i18n]').textContent=LANG[currentLang].startDetect;$('jamBtn').querySelector('[data-i18n]').textContent=LANG[currentLang].engageJam;log('Reset','info');playSound('click');};
}

document.addEventListener('DOMContentLoaded',()=>{
  initSplash();initPanels();initLogFilters();initDrones();initTechDatabase();initControls();
  try{const l=localStorage.getItem('wdiy-lang');if(l)setLanguage(l);}catch{}
  try{const t=localStorage.getItem('wdiy-theme');if(t)setTheme(t);}catch{}
  log(LANG[currentLang].ready,'success');animate();setInterval(updateDroneList,1000);
});
