#!/usr/bin/env python3
"""
Pi NEC Antenna Simulator
Runs NEC2 electromagnetic simulation engine on Raspberry Pi.
Generates antenna radiation patterns and provides web visualization.
"""

import os
import sys
import math
import json
import subprocess
import tempfile
import logging
from pathlib import Path
from flask import Flask, jsonify, request, render_template_string

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("nec-simulator")

app = Flask(__name__)

NEC2_BIN = "/usr/local/bin/nec2c"
RESULTS_DIR = Path("/var/lib/pi-nec/results")
RESULTS_DIR.mkdir(parents=True, exist_ok=True)


class NEC2Engine:
    """Interface to NEC2 electromagnetic simulation engine."""

    def __init__(self):
        self.last_result = None
        self.simulations = []

    def generate_dipole_card(self, freq_mhz, length_m, segments=21, wire_radius=0.001):
        """Generate NEC2 input card for a simple dipole antenna."""
        half_len = length_m / 2.0
        card = f"""CM Dipole Antenna at {freq_mhz} MHz
CM Generated by Pi NEC Simulator
CE
GW 1 {segments} 0.0 -{half_len:.4f} 0.0 0.0 {half_len:.4f} 0.0 {wire_radius:.6f}
GE 0
GN -1
EK
EX 0 1 {(segments + 1) // 2} 0 1.0 0.0
FR 0 1 0 0 {freq_mhz:.3f} 0.0
RP 0 37 73 1000 -90.0 0.0 5.0 5.0
EN
"""
        return card

    def generate_yagi_card(self, freq_mhz, num_elements=3):
        """Generate NEC2 input card for a Yagi-Uda antenna."""
        wavelength = 300.0 / freq_mhz
        spacing = wavelength * 0.2
        driven_len = wavelength * 0.475 / 2.0
        reflector_len = wavelength * 0.5 / 2.0
        director_len = wavelength * 0.44 / 2.0

        lines = [
            f"CM {num_elements}-element Yagi at {freq_mhz} MHz",
            "CE",
            f"GW 1 21 0.0 -{reflector_len:.4f} 0.0 0.0 {reflector_len:.4f} 0.0 0.001",
            f"GW 2 21 {spacing:.4f} -{driven_len:.4f} 0.0 {spacing:.4f} {driven_len:.4f} 0.0 0.001",
        ]
        for i in range(num_elements - 2):
            x_pos = spacing * (i + 2)
            lines.append(
                f"GW {i+3} 21 {x_pos:.4f} -{director_len:.4f} 0.0 "
                f"{x_pos:.4f} {director_len:.4f} 0.0 0.001"
            )
        lines.extend([
            "GE 0", "GN -1", "EK",
            "EX 0 2 11 0 1.0 0.0",
            f"FR 0 1 0 0 {freq_mhz:.3f} 0.0",
            "RP 0 37 73 1000 -90.0 0.0 5.0 5.0",
            "EN",
        ])
        return "\n".join(lines) + "\n"

    def run_simulation(self, nec_card, name="simulation"):
        """Execute NEC2 simulation and parse results."""
        with tempfile.NamedTemporaryFile(mode="w", suffix=".nec", delete=False) as inf:
            inf.write(nec_card)
            input_file = inf.name

        output_file = input_file.replace(".nec", ".out")

        try:
            result = subprocess.run(
                [NEC2_BIN, "-i", input_file, "-o", output_file],
                capture_output=True, text=True, timeout=120
            )
            if result.returncode != 0:
                logger.error("NEC2 failed: %s", result.stderr)
                return {"error": result.stderr}

            parsed = self._parse_output(output_file)
            parsed["name"] = name
            self.last_result = parsed
            self.simulations.append(parsed)

            # Save result
            out_path = RESULTS_DIR / f"{name}_{len(self.simulations)}.json"
            with open(out_path, "w") as f:
                json.dump(parsed, f, indent=2)

            return parsed

        except subprocess.TimeoutExpired:
            return {"error": "Simulation timed out"}
        finally:
            for f in [input_file, output_file]:
                if os.path.exists(f):
                    os.unlink(f)

    def _parse_output(self, output_file):
        """Parse NEC2 output file for radiation pattern and impedance."""
        pattern = []
        impedance = None
        gain_max = -999.0

        with open(output_file) as f:
            in_rp_section = False
            for line in f:
                if "RADIATION PATTERNS" in line:
                    in_rp_section = True
                    continue
                if in_rp_section and line.strip() and line[0].isspace():
                    parts = line.split()
                    if len(parts) >= 7:
                        try:
                            theta = float(parts[0])
                            phi = float(parts[1])
                            gain_db = float(parts[4])
                            pattern.append({"theta": theta, "phi": phi, "gain_db": gain_db})
                            gain_max = max(gain_max, gain_db)
                        except (ValueError, IndexError):
                            pass
                if "IMPEDANCE" in line and "REAL" in line:
                    parts = line.split()
                    try:
                        impedance = {"real": float(parts[-2]), "imag": float(parts[-1])}
                    except (ValueError, IndexError):
                        pass

        return {
            "pattern": pattern,
            "impedance": impedance,
            "gain_max_dbi": round(gain_max, 2),
            "num_points": len(pattern),
        }

    def calculate_swr(self, impedance, z0=50.0):
        """Calculate SWR from complex impedance."""
        if not impedance:
            return None
        r = impedance["real"]
        x = impedance["imag"]
        z_mag = math.sqrt(r**2 + x**2)
        gamma = abs((complex(r, x) - z0) / (complex(r, x) + z0))
        if gamma >= 1.0:
            return 999.0
        return round((1 + gamma) / (1 - gamma), 2)


engine = NEC2Engine()


@app.route("/")
def index():
    return render_template_string("""
    <html><head><title>Pi NEC Simulator</title></head><body>
    <h1>NEC2 Antenna Simulator</h1>
    <p>Use the API to run simulations.</p>
    </body></html>
    """)

@app.route("/api/simulate/dipole", methods=["POST"])
def simulate_dipole():
    data = request.json or {}
    freq = data.get("freq_mhz", 145.0)
    length = data.get("length_m", 300.0 / freq * 0.475)
    card = engine.generate_dipole_card(freq, length)
    result = engine.run_simulation(card, name=f"dipole_{freq}MHz")
    result["swr"] = engine.calculate_swr(result.get("impedance"))
    return jsonify(result)

@app.route("/api/simulate/yagi", methods=["POST"])
def simulate_yagi():
    data = request.json or {}
    freq = data.get("freq_mhz", 145.0)
    elements = data.get("elements", 3)
    card = engine.generate_yagi_card(freq, elements)
    result = engine.run_simulation(card, name=f"yagi_{elements}el_{freq}MHz")
    result["swr"] = engine.calculate_swr(result.get("impedance"))
    return jsonify(result)

@app.route("/api/results")
def list_results():
    files = sorted(RESULTS_DIR.glob("*.json"))
    return jsonify({"results": [f.stem for f in files], "count": len(files)})

@app.route("/api/status")
def status():
    return jsonify({
        "nec2_available": os.path.exists(NEC2_BIN),
        "total_simulations": len(engine.simulations),
        "last_result": engine.last_result,
    })


if __name__ == "__main__":
    logger.info("Starting Pi NEC Simulator on port 8081")
    if not os.path.exists(NEC2_BIN):
        logger.warning("nec2c binary not found at %s - install with: sudo apt install nec2c", NEC2_BIN)
    app.run(host="0.0.0.0", port=8081, debug=False)
